### PR TITLE
Split different linters into different jobs.

### PR DESCRIPTION
**Pull request by cheshire**

### CODE REVIEW

**Comment by PhilippWendler** [comment]
I think I have seen a trick somewhere to add a environment variable like `CHECK` and set it to a distinct value in each config. The variable does not need to be used somewhere, but it is shown on the Travis website and be used to distinguish the individual builders there.

**Comment by PhilippWendler** [comment]
I am not sure whether deployment is done for all matrix configs? If yes, we should probably add something to execute them only where desired, if not, the javadoc builder needs to run in the main config where the deployment is done. `build-project-ecj` can be in a separate config, though.

**Comment by cheshire** [comment]
> I think I have seen a trick somewhere to add a environment variable like CHECK and set it to a distinct value in each config. 

Yep, should do this.

> I am not sure whether deployment is done for all matrix configs?

Good point, don't know now, will check.

**Comment by cheshire** [comment]
I'm afraid I will have to just merge it in order to see how deployment is done for the matrix.

**Pull request merged**
