### PR TITLE
Extend Maven Support

### PR DESCRIPTION
**Pull request by kfriedberger**
This PR aims to solve #201 by improving the support and documentation for Maven when using JavaSMT.

### CODE REVIEW

**Comment by baierd** [comment]
ocbea16 is my first draft of a documentation/starting point that should help every dev/maintainer if an Maven related issue should arise.

**Comment by kfriedberger** [comment]
@baierd
From the Maven point it looks as good as possible before merging into trunk.
Is there anything very important that you still want to fix in this branch?
Otherwise I would merge this branch soon and then publish a new release, including a Maven release.
That release would be provided to a potentially larger user group.

**Comment by baierd** [comment]
Looks good from my point of view.
The only thing missing that i'd like to add is Windows support for Maven. But that can be done on another branch.

**Comment by kfriedberger** [comment]
Isn't Maven on Windows the same as on Linux?
I already published the Windows binaries for Z3 and they seemed to work.

Ok, I will merge this PR, then update some solvers (Z3 had a new version yesterday) and then provide a full Maven release for extensive testing.

**Pull request merged**
