### PR TITLE
WIP Boolector v3.1.0 update

### PR DESCRIPTION
**Pull request by kfriedberger**
This issue can be used to discuss further steps when updating the SMT solver Boolector.

### CODE REVIEW

**Comment by kfriedberger** [comment]
@baierd 
- Does updating Boolector not need any change in the source file for the wrapper script? Is there no new API feature?
- Could you rebase this whole branch on top of the master branch? This would enable Java 11 and use some more CI checks.

**Comment by baierd** [comment]
@kfriedberger 

- Should i add the new API calls preemptively?

They added a few convenience functions, but we solved the problems the new API calls solve mainly in our own code ourselfs. (max value for signed bitvector for example)

- Sure thing, i'll rebase

**Comment by baierd** [comment]
New version (3.2.0) released today. 
It may be possible to integrate Parsing now.

**Comment by baierd** [comment]
Move to boolector_v3.2.0_update branch for further discussion

**Pull request closed without merging**
